/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  // static const String? _kFontPkg = null;

  static const IconData chicken_leg = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData chinese_food = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData coffee_cup = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData croissant = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData cutlery = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData big_cheeseburger = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData pizza_slice = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData salad = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData sandwich = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData seafood = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData spaghetti = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData nigiri = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData taco = IconData(0xe812, fontFamily: _kFontFam);
}
